# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gugora/SpAlgoritmos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gugora/SpAlgoritmos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gugora/SpAlgoritmos/CMakeFiles /home/gugora/SpAlgoritmos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gugora/SpAlgoritmos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SituacionProblema

# Build rule for target.
SituacionProblema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SituacionProblema
.PHONY : SituacionProblema

# fast build rule for target.
SituacionProblema/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/build
.PHONY : SituacionProblema/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named make_and_run

# Build rule for target.
make_and_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 make_and_run
.PHONY : make_and_run

# fast build rule for target.
make_and_run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make_and_run.dir/build.make CMakeFiles/make_and_run.dir/build
.PHONY : make_and_run/fast

src/DataCoverter.o: src/DataCoverter.cpp.o
.PHONY : src/DataCoverter.o

# target to build an object file
src/DataCoverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/DataCoverter.cpp.o
.PHONY : src/DataCoverter.cpp.o

src/DataCoverter.i: src/DataCoverter.cpp.i
.PHONY : src/DataCoverter.i

# target to preprocess a source file
src/DataCoverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/DataCoverter.cpp.i
.PHONY : src/DataCoverter.cpp.i

src/DataCoverter.s: src/DataCoverter.cpp.s
.PHONY : src/DataCoverter.s

# target to generate assembly for a file
src/DataCoverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/DataCoverter.cpp.s
.PHONY : src/DataCoverter.cpp.s

src/Order.o: src/Order.cpp.o
.PHONY : src/Order.o

# target to build an object file
src/Order.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/Order.cpp.o
.PHONY : src/Order.cpp.o

src/Order.i: src/Order.cpp.i
.PHONY : src/Order.i

# target to preprocess a source file
src/Order.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/Order.cpp.i
.PHONY : src/Order.cpp.i

src/Order.s: src/Order.cpp.s
.PHONY : src/Order.s

# target to generate assembly for a file
src/Order.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/Order.cpp.s
.PHONY : src/Order.cpp.s

src/OrderManager.o: src/OrderManager.cpp.o
.PHONY : src/OrderManager.o

# target to build an object file
src/OrderManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/OrderManager.cpp.o
.PHONY : src/OrderManager.cpp.o

src/OrderManager.i: src/OrderManager.cpp.i
.PHONY : src/OrderManager.i

# target to preprocess a source file
src/OrderManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/OrderManager.cpp.i
.PHONY : src/OrderManager.cpp.i

src/OrderManager.s: src/OrderManager.cpp.s
.PHONY : src/OrderManager.s

# target to generate assembly for a file
src/OrderManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/OrderManager.cpp.s
.PHONY : src/OrderManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SituacionProblema.dir/build.make CMakeFiles/SituacionProblema.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... make_and_run"
	@echo "... run"
	@echo "... SituacionProblema"
	@echo "... src/DataCoverter.o"
	@echo "... src/DataCoverter.i"
	@echo "... src/DataCoverter.s"
	@echo "... src/Order.o"
	@echo "... src/Order.i"
	@echo "... src/Order.s"
	@echo "... src/OrderManager.o"
	@echo "... src/OrderManager.i"
	@echo "... src/OrderManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

